### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sarmadm** [burgess666/UCF101_video_classification#1]
Hi

Can you please help me with this error : 

`Traceback (most recent call last):
  File "1_move_files.py", line 81, in <module>
    main()
  File "1_move_files.py", line 78, in main
    move_files(group_lists)
  File "1_move_files.py", line 49, in move_files
    filename = parts[1]
IndexError: list index out of range
`

**Comment by kaiqiangh** [comment]
Hi,

I think it could be caused by your video paths. The video path should just be in the data directory (not in any sub-directory) before running 1_move files.py script.

**Comment by sarmadm** [comment]
I put all videos directly in data folder as .avi files but it still not working : 

`(keras_v) C:\Users\Documents\deep_L_projects\UCF101_video_classification-master\data>python 1_move_files.py
Traceback (most recent call last):
  File "1_move_files.py", line 76, in <module>
    main()
  File "1_move_files.py", line 73, in main
    move_files(group_lists)
  File "1_move_files.py", line 44, in move_files
    filename = parts[1]
IndexError: list index out of range`

**Comment by kaiqiangh** [comment]
Did you create train and test as sub-folder in data directory?

**Comment by sarmadm** [comment]
Yes , please see below pictures shows train , test and videos , is that correct ?

![folders](https://user-images.githubusercontent.com/14107864/48127011-a2cc8500-e27a-11e8-8636-50e44f715835.JPG)

**Comment by kaiqiangh** [comment]
Yes, it's correct. I suggest you'd better remove data_file.csv, classInd.txt and README.md file out of data directory. And try it again.

**Comment by sarmadm** [comment]
I done what you suggested but it is still Showing same error
`(keras_v) C:\Users\Documents\deep_L_projects\UCF101_video_classification-master\data>python 
1_move_files.py
Traceback (most recent call last):
  File "1_move_files.py", line 76, in <module>
    main()
  File "1_move_files.py", line 73, in main
    move_files(group_lists)
  File "1_move_files.py", line 44, in move_files
    filename = parts[1]
IndexError: list index out of range`

**Comment by kaiqiangh** [comment]
just for sure, do you only have the sub-folders, py files and .avi files? no other files in data dir?

**Comment by sarmadm** [comment]
No as shown in the picture , only these folders
